# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada4f32422404acfd740fc2a5582b8432053f7e65fe68303307557e920596549c68d58b14cf1fae872b2897868a45c94b10f88aea82e1dda051f087d60b8f25d

test:
  secret_key_base: 4abd544002002eee99ea034d6c8096f2cfc524d9543bea12b346e18e14da553eed82a3e5ed1f9d1eb810627695bae2dd627c43c72dee8e53daccc27946741610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
